apiVersion: v1
kind: Pod
metadata: 
  name: corona-pod
  labels:
    appName: corona
spec:
  containers: 
  - name: corona
    image: mohommadali/corona:1.0
    ports:
    - name: tomcatport
      containerPort: 8081
      protocol: TCP
    readinessProbe: 
      httpGet: 
        path: /actuator/health/readiness
        port: 8081
      initialDelaySeconds: 10
      timeoutSeconds: 20
      failureThreshold: 5
    livenessProbe:
      httpGet: 
        path: /actuator/health/liveness
        port: 8081
      initialDelaySeconds: 10
      timeoutSeconds: 20
      failureThreshold: 5
    resources:
      requests:
        cpu: "1000m"
        memory: "1024Mi"
      limits: 
        cpu: "1000m"
        memory: "1024Mi"
    env:
      - name: guidelines.oxygenLevels
        valueFrom:
          configMapKeyRef:
            name: guidelinesconfigmap
            key: oxygenLevels
      - name: guidelines.quarantine
        valueFrom: 
          configMapKeyRef:
            name: guidelinesconfigmap
            key: quarantine
      - name: guidelines.liters
        valueFrom: 
          configMapKeyRef:
            name: guidelinesconfigmap
            key: liters 
      - name: guidelines.temparatureLevels
        valueFrom:
          configMapKeyRef: 
            name: guidelinesconfigmap
            key: temparatureLevels   
    volumeMount:
      - name: healthinspectorvolume
        path: "/config"
        readOnly: true
  volume: 
    - name: healthinspectorvolume
      configmap:
        name: ealthinspectorconfigmap
          - key: district-healthinspectors.properties
            path: "district-healthinspectors.properties"      